syntax = "proto3";

import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";

package pricing.v1;

option csharp_namespace = "PricingService.Api.Grpc.V1.Protos";

service PricingService {
	rpc CreatePrice(CreatePriceRequest) returns (google.protobuf.Empty);
    rpc GetPriceByProductId(GetPriceByProductIdRequest) returns (GetPriceByProductIdResponse);
}

message PriceDto {
    string product_id = 1;
    int64 base_price_minor = 2;
    int64 current_price_minor = 3;
    string currency = 4;
    DiscountDto discount = 5;
}

message DiscountDto {
    string discount_id = 1;
    DiscountType type = 2;
    double percentage = 3;
    int64 fixed_price_minor = 4;
    int64 amount_off_minor = 5;
    string campaign_name = 6;
    int32 priority = 7;
    bool is_stackable = 8;
    google.protobuf.Timestamp start = 9;
    google.protobuf.Timestamp end = 10;
}

enum DiscountType {
    PERCENTAGE = 0;
    FIXED_PRICE = 1;
    AMOUNT_OFF = 2;
}

message CreatePriceRequest {
    string product_id = 1;
    string vendor_id = 2; 
    int64 base_price_minor = 3;
    string currency = 4;
}

message GetPriceByProductIdRequest {
    string product_id = 1;
    string currency = 2;
}

message GetPriceByProductIdResponse {
    PriceDto price = 1;
}