using MediatR;

namespace PricingService.Application.Features.IntegrationEventHandlers.ProductVariantSnapshot.DeleteProductVariantSnapshot;

public sealed record DeleteProductVariantSnapshotCommand(Guid ProductVariantId) : IRequest;